### ISSUE TITLE
Error Sudoku fácil

### ISSUE THREAD

**Issue by ViqJ** [santifiorino/sudoku.com-solver#4]
Saludos, espero se encuentre bien, me encantan sus videos, estaba probando el código y me encontré con un caso particular en el momento que lo puse en fácil, te comparto imagen.

![image](https://github.com/santifiorino/sudoku.com-solver/assets/139706657/6acd3646-f93d-42d9-bba7-df3c70880ecd)

Me pareció extraño que fallara, igual está buenisimo y resuelve los casos de demoníaco en decimas por si querías analizarlo.

**Comment by santifiorino** [comment]
Hay varias opciones, la primera es que el modelo de kNN haya identificado mal algún número, casi nunca pasa pero durante el desarrollo me ha pasado. La segunda es que a veces es tan rápida la función que mueve el mouse y toca las teclas que el navegador o el SO no llega a procesarlo bien y se desfasa. En esos casos te das cuenta porque si reinicias el nivel y lo corrés de nuevo ahí ya anda. El algoritmo en sí de backtracking que lo resuelve no puede fallar, así que es una de esas dos cosas!

**Comment by ViqJ** [comment]
Claro, me parece que tienes razón, la lógica no va a fallar pero la lectura o escritura si está expuesta a fallos, muchas gracias.
